Chore follow the color output input
orhanna14/task-it-to-me pull request #6
Opened 2020-04-17 23:23 UTC by orhanna14

Related to [this PR](https://github.com/orhanna14/task-it-to-me/pull/5), this PR focuses on abstracting the printing related methods into their own `output_stream` and `input_stream` classes.

2020-04-17 23:35 UTC, baccigalupi requested changes
This is a lot more focused! Thanks.

I think when you extract objects you should be thinking about the names of the methods. You came up with really great methods names. Related to the output steam, you have two categories of things, prompts and prints. It seems to me those are your objects: `Prompt.new(output_stream).project_name`, etc. Also, one of the rules for refactoring is that new classes shouldn't be any longer than 100 lines. So, something has to change anyway in the Output class.

When you extract these into differently named object, think about how to name the instances of those objects and also what that means about shortening the names of the methods.

You are getting there!

2020-04-18 16:01 UTC, baccigalupi approved these changes
This is a lot farther that I would probably have gone. What I saw based on your naming, was just the printer class and the prompt class. All these classes are pretty easy to understand though. I am interested to know how it will play out.

One of the worries about pulling out too much logic is separating patterns. For example, each of the printer classes now has all this escape code gunk, and it's harder to see if there is a pattern in the gunk.

Also, I think you could still get more consistent in the naming of methods in theses classes. That will pay off in dividends as you are both reading code, and trying to understand how it holds together in the future.

This is great work though! And you should decide for yourself whether you want to do another pass through the work.

2020-04-18 16:01 UTC, baccigalupi commented on lib/app.rb
> +  def initialize(stdout, stdin)
Wow! Lots of printerns!

2020-04-18 16:01 UTC, baccigalupi commented on lib/app.rb
> +            line_printer.single
This `line_printer` seems like too much. Since this is really about printing each project with a boundary, I would just jam this in there for now. It reminds me a bit of the work you did before of removing data related ivars, but keeping all the data logic behind. There is definitely a smell here, but this separates that smell from its origin.

2020-04-18 16:01 UTC, baccigalupi commented on lib/project_printer.rb
> +class ProjectPrinter
I noticed in this class that some of the methods have `project` or `projects` in them, and some don't. It would be good to get consistent.

2020-04-20 16:33 UTC, orhanna14 commented on lib/project_printer.rb
> +class ProjectPrinter
Ah, yes, I did that on purpose because they were either related to a single project or multiple projects.

2020-04-20 16:40 UTC, orhanna14 commented on lib/app.rb
> +            line_printer.single
✔️

2020-04-20 16:42 UTC, orhanna14 commented
Yeah! I originally had the `printer` and `prompter` classes, but you had mentioned that new classes need to be 100 lines or less when refactoring, so I separated the `printer` class to follow this rule.

2020-04-20 16:44 UTC, merged